### ISSUE TITLE
HTML Element Shown in JSON

### ISSUE THREAD

**Issue by RainzDev** [Quaver/api-v2#111]
I'm not exactly sure if it's a bug or not, but there's a p element in the `about_me` value. `"\u003Cp\u003Eplaceholder about me. (warp is cool)\u003C/p\u003E",` (for example). 

https://api.quavergame.com/v2/clan/:id

If this is intended, then removing it from the value would be nice in my opinion, instead of devs manually having to remove it when they're using the API.

**Comment by Swan** [comment]
The about_me section allows for custom HTML for formatting, so it's not a bug
