### ISSUE TITLE
RS Action comments active not working correctly

### ISSUE THREAD

**Issue by AiAe** [Quaver/api-v2#55]
If mapset is on hold, and then we deny it, the on hold comment is still active, and it should not be.
Probably its also broken for the other cases of action order?

**Comment by AiAe** [comment]
Submitting rs comment is also marked directly as active false, it should be true, until some action is taken that needs to mark it as inactive

**Comment by Swan** [comment]
The active state just means that the action counts towards the current ranking "session." 

The ranking session (and all previous actions) are marked as inactive when the amount of votes reset (which is when the user re-submits for rank). So if you on-hold and then deny, nothing was reset, and all actions for that session should still be active until the user resubmits.

 > Submitting rs comment is also marked directly as active false, it should be true, until some action is taken that needs to mark it as inactive

I'll fix this.

**Comment by AiAe** [comment]
> The ranking session (and all previous actions) are marked as inactive when the amount of votes reset (which is when the user re-submits for rank). So if you on-hold and then deny, nothing was reset, and all actions for that session should still be active until the user resubmits.

Yea I see, this makes sense.

**Comment by Swan** [comment]
Resolved in https://github.com/Quaver/api-v2/commit/95add71b6ab4f65a19822046c0d6d6fc1b14b442
